#!/usr/bin/env ruby

require 'yaml'
require 'fileutils'
require 'shellwords'
require 'digest/sha2'
require 'ostruct'
require 'optionparser'

begin
  require 'rotp'
  HAS_OTP = true
rescue LoadError
  HAS_OTP = false
end

BROWSERS = %w[chrome chromium firefox opera]

config_dir = ENV['XDG_CONFIG_HOME'] || "#{ENV['HOME']}/.config"
config_file = File.join(config_dir, 'autopass', 'config.yml')
unless File.exist?(config_file)
  FileUtils.mkdir_p(File.dirname(config_file))
  File.write config_file, <<EOF
---
# you can insert any environment variable inside %{} for it to be replaced by
# the value of that variable. If it needs to be at the beginning of the string
# you have to escape it (e.g. `foo: %{BAR}` will raise an error, `foo: '%{BAR}'`
# will work though)

cache_file: '%{HOME}/.cache/autopass/autopass.cache'
# cache_key: YOUR_KEY_ID
# key_bindings:
#   autotype_tan: Alt+t
#   copy_username: Alt+u
#   copy_password: Alt+p
#   open_browser: Alt+o

# clipboard command to use:
# (default)
#   clip_command: 'xclip'
# or
#   clip_command: 'xclip -selection clipboard'
EOF
  puts "Copied example config to #{config_file}"
  puts 'Please edit and set the gpg key to use for decrypting the cache'
  exit
end

SYM_ENV = Hash[ENV.map { |var, value| [var.to_sym, value] }]

def expand_config(item)
  case item
  when Hash
    ostruct = OpenStruct.new
    item.each { |key, value| ostruct[key] = expand_config(value) }
    ostruct
  when Array then item.map(&method(:expand_config))
  when String
    if item =~ /%\{.+\}/
      item % SYM_ENV
    else
      item
    end
  else item
  end
end

class OpenStruct
  def merge!(other)
    other.each_pair do |key, value|
      own_value = self[key]
      self[key] = if value.is_a?(OpenStruct) && own_value.is_a?(OpenStruct)
                    own_value.merge!(value)
                  else
                    value
                  end
    end
    self
  end

  def reverse_merge!(other)
    other.each_pair do |key, value|
      own_value = self[key]
      self[key] = if value.is_a?(OpenStruct) && own_value.is_a?(OpenStruct)
                    own_value.reverse_merge!(value)
                  elsif own_value.nil?
                    value
                  else
                    own_value
                  end
    end
    self
  end
end

DEFAULT_CONFIG = expand_config(
  prompt: 'Search:',
  cache_file: '%{HOME}/.cache/autopass/autopass.cache',
  password_store: '%{HOME}/.password-store',
  username_key: 'user',
  password_key: 'pass',
  autotype_3: ':otp',
  key_bindings: {
    copy_username: 'Alt+u',
    copy_password: 'Alt+p',
    autotype_tan: 'Alt+t',
    open_browser: 'Alt+o',
    copy_otp: 'Alt+c'
  },
  alt_delay: 0.5,
  clip_command: 'xclip',
)

CONFIG = expand_config(YAML.load_file(config_file))
CONFIG.reverse_merge!(DEFAULT_CONFIG)
CONFIG[:autotype_1] ||= CONFIG[:password_key]
CONFIG[:autotype_2] ||= CONFIG[:username_key]

OptionParser.new do |opts|
  opts.banner = "Usage: #{File.basename(__FILE__)} [OPTIONS]"
  opts.separator ""
  opts.separator 'Rofi frontend for pass and copy or autotype your passwords.'
  opts.separator ""
  opts.separator "OPTIONS:"

  opts.on('-c', '--clear-cache', "Remove cache file") do
    if File.exist? CONFIG.cache_file
      File.delete(CONFIG.cache_file)
      puts "rm #{CONFIG.cache_file}"
    end
    exit
  end

  opts.on("-h", "--help", "Show this help message") do
    puts opts
    exit
  end
end.parse!

unless Dir.exist?(CONFIG.password_store)
  abort('It seems that you havent set up a password store yet. Do so by running `pass init <YOUR_KEY_ID>`')
end

def notify(message, type = :normal, milliseconds = 5000)
  system('notify-send', '-a', File.basename(__FILE__, '.rb').to_s, '-u', type.to_s, '-t', milliseconds.to_s, message.to_s)
end

class Entry
  attr_reader :name, :attributes

  def initialize(name, attributes = OpenStruct.new)
    @name = name
    @attributes = attributes
  end

  def autotype!(index = 0)
    keys = autotype_keys(index)
    if autotype_values(keys).empty?
      notify("No key '#{keys.join('+')}' found for this entry!", :critical)
      return
    end
    sleep CONFIG.alt_delay if index > 0
    focus_window!
    perform_autotype(autotype_values(keys))
  end

  def autotype_tan
    tan = nil
    unless attributes.tan
      notify('This entry has no tan attribute', :critical)
      exit
    end

    tans = attributes.tan.lines
    loop do
      tan_number = ask_tan_number
      tan = tans[tan_number - 1]
      break if tan
      notify("No TAN at index #{tan_number}", :critical)
    end
    focus_window!
    perform_autotype([tan.strip])
  end

  def otp
    unless HAS_OTP
      $stderr.puts("Couldn't require rotp. Install it with `gem install rotp`")
      notify('Couldn\'t require rotp. Install it with `gem install rotp`', :critical)
      exit 1
    end
    unless attributes.otp_secret
      $stderr.puts([
        'No OTP secret found for this entry.',
        'Make sure your entry contains an attribute `otp_secret` like the following:',
        'otp_secret: your_otp_secret'
      ])
      notify('No OTP secret found for this entry.', :critical)
      exit 1
    end
    ROTP::TOTP.new(attributes.otp_secret).now
  end

  def autotype_values(keys)
    keys.map { |key| key[0] == ':' ? key : attributes[key] }.compact
  end

  def autotype_keys(index)
    keys = case index
           when 0
             autotype_key = CONFIG.autotype_key || 'autotype'
             attributes[autotype_key] || CONFIG[autotype_key] || [CONFIG.username_key, ':tab', CONFIG.password_key]
           when 1 then attributes.autotype_1 || CONFIG.autotype_1
           when 2 then attributes.autotype_2 || CONFIG.autotype_2
           when 3 then attributes.autotype_3 || CONFIG.autotype_3
           else attributes[:"autotype_#{index}"] || CONFIG[:"autotype_#{index}"] || []
           end
    keys = keys.split(/\s+/) if keys.is_a?(String)
    keys
  end

  def focus_window!
    `xdotool windowfocus --sync #{window_id}`
  end

  def window_id
    [
      attributes.window, # try window
      Regexp.escape(attributes.url || ''), # try url
      "#{attributes.window}.*#{Regexp.union(BROWSERS)}", # try window with browser
      Regexp.escape(name || '') # try name
    ].each do |regex|
      output = search_window_id(regex)
      return output.to_i if output.lines.size == 1
    end

    select_window_id_by_user!
  end

  def match(window_name)
    window_name.match(/#{attributes.window || Regexp.escape(attributes.url || name)}/i)
  end

  def search_window_id(window_regex)
    `xdotool search --onlyvisible --name #{Shellwords.escape(window_regex)}`.chomp
  end

  def select_window_id_by_user!
    notify('Please select the target window')
    xwininfo = `xwininfo -int`
    title = xwininfo.match(/Window id: \d+ "(?<title>.*)"$/)[:title]
    print "selected window: `#{title}` "
    IO.popen(CONFIG.clip_command, 'w+') do |io|
      io.write(title)
      io.close_write
    end
    puts 'copied to clipboard'
    xwininfo[/(?<=Window id: )\d+/]
  end

  def open_url!
    if attributes.url.to_s.empty?
      notify('Cannot find URL in entry', :critical)
    else
      system(ENV['BROWSER'] || 'xdg-open', attributes.url)
    end
  end

  private

  def perform_autotype(values)
    values.each do |value|
      case value
      when ':tab' then `xdotool key Tab`
      when ':enter' then `xdotool key Return`
      else
        type = value == ':otp' ? otp : value
        IO.popen('xdotool type --clearmodifiers --file -', 'w+') do |io|
          io.write(type)
          io.close_write
        end
      end
    end
  end

  def ask_tan_number
    number = nil
    loop do
      IO.popen('rofi -dmenu -p "TAN number:"', 'w+') do |io|
        io.close_write
        number = io.gets
      end
      exit if number.nil?
      break if number.to_i.to_s == number.strip
      notify('Please enter a number')
    end
    number.to_i
  end
end

class PassBackend
  def initialize
    fail('cache_key option not defined') unless CONFIG.cache_key
    init_cache
    @needs_saving = false
    update_cache
    save_cache if needs_saving?
  end

  def entries
    @cache[:entries]
  end

  def sorted_entries(focused_window)
    Hash[
      entries.sort_by do |name, entry|
        match = entry.match(focused_window)
        match ? "\0" * focused_window.sub(match[0], '').size : name
      end
    ]
  end

  private

  def save_cache
    File.delete(CONFIG.cache_file) if File.exist?(CONFIG.cache_file)
    gpg_cmd = 'gpg -eq --batch -r '\
              "#{CONFIG.cache_key}"
    FileUtils.mkdir_p(File.dirname(CONFIG.cache_file))
    IO.popen(gpg_cmd, 'w+') do |io|
      io.puts(Marshal.dump(@cache))
      io.close_write
      File.open(CONFIG.cache_file, 'wb+', perm: 0600) do |f|
        f.write(io.read)
      end
    end
  end

  def entry_from(file)
    name = file.sub(/\.gpg$/, '')
    content = `pass show #{Shellwords.escape(name)}`
    pass = content.lines.first.chomp
    yaml = (content.lines[1..-1] || []).join
    begin
      metadata = expand_config(YAML.load(yaml) || {})
    rescue Psych::SyntaxError => e
      $stderr.puts "Failed parsing yaml of entry '#{name}':"
      $stderr.puts yaml
      $stderr.puts e.message
      metadata.error = true
      metadata.error_message = e.message
    end
    begin
      metadata.merge!(CONFIG.password_key => pass)
    rescue NoMethodError => e
      metadata = OpenStruct.new(error: true)
      metadata.error_message = e.message
    end

    Entry.new(
      File.basename(name),
      metadata
    )
  end

  def files
    result = nil
    FileUtils.cd(CONFIG.password_store) do
      result = Dir['**/*.gpg']
    end
    result
  end

  def needs_saving?
    @needs_saving
  end

  def update_cache
    checksums.each do |file, checksum|
      next if @cache[:checksums][file] == checksum
      @cache[:entries][file.sub(/\.gpg$/, '')] = entry_from(file)
      @cache[:checksums][file] = checksum
      @needs_saving = true
    end
  end

  def checksums
    result = nil
    FileUtils.cd(CONFIG.password_store) do
      result = Hash[
        files.map { |file| [file, Digest::SHA512.file(file).hexdigest] }
      ]
    end
    result
  end

  def init_cache
    if File.exist?(CONFIG.cache_file)
      @cache = Marshal.load(`gpg -dq --batch #{CONFIG.cache_file}`)
    else
      @cache = { checksums: {}, entries: {} }
    end
  end
end

focused_window_id = `xdotool getwindowfocus`.chomp.to_i
focused_window_name = `xdotool getwindowname #{focused_window_id}`
pass_backend = PassBackend.new

choice = nil

sorted_entries = pass_backend.sorted_entries(focused_window_name)
errorneus_entry_indices = sorted_entries.each_with_index.reduce([]) do |result, ((_, entry), i)|
  entry.attributes.error == true ? result << i : result
end

rofi_args = %W(-dmenu -i -z -p #{CONFIG.prompt})
rofi_args.concat(['-kb-custom-7', CONFIG.key_bindings.autotype_tan])
rofi_args.concat(['-kb-custom-8', CONFIG.key_bindings.copy_password])
rofi_args.concat(['-kb-custom-9', CONFIG.key_bindings.copy_username])
rofi_args.concat(['-kb-custom-10', CONFIG.key_bindings.open_browser])
rofi_args.concat(['-kb-custom-11', CONFIG.key_bindings.copy_otp])
rofi_args << '-mesg'
msgs = [
  "Alt-1: Autotype #{CONFIG.autotype_1}",
  "Alt-2: Autotype #{CONFIG.autotype_2}",
  "Alt-3: Autotype #{CONFIG.autotype_3}",
  "Alt-{4-6}: Alternative autotypes",
  "#{CONFIG.key_bindings.autotype_tan}: Autotype TAN",
  "#{CONFIG.key_bindings.copy_password}: Copy password",
  "#{CONFIG.key_bindings.copy_username}: Copy username",
  "#{CONFIG.key_bindings.copy_otp}: Copy OTP-Code",
  "#{CONFIG.key_bindings.open_browser}: Open URL in browser"
]
half = (msgs.length / 2.0).ceil
msgs = msgs.first(half).map.with_index do |msg, index|
  left = msg.to_s.ljust(40, ' ')
  right = msgs[half+index]
  [left, right].join
end
rofi_args << msgs.join("\n")


unless errorneus_entry_indices.empty?
  rofi_args.concat(['-u', errorneus_entry_indices.join(',')])
end

IO.popen(['rofi', *rofi_args], 'w+') do |io|
  io.puts(*sorted_entries.keys)
  io.close_write
  choice = io.gets
  exit if choice.nil?
end

return_value = $?.exitstatus

@entry = pass_backend.entries[choice.chomp]
if @entry.attributes.error == true
  system('rofi', '-e', @entry.attributes.error_message)
  exit 1
end

def copy(attribute, notification_seconds = 5)
  clear_clip_pidfile = '/tmp/autopass-clear-clip.pid'
  value = attribute == :otp ? @entry.otp : @entry.attributes[attribute]

  if File.exist?(clear_clip_pidfile)
    Process.kill(:INT, File.read(clear_clip_pidfile).to_i)
  end
  IO.popen(CONFIG.clip_command, 'w+') { |io| io.print(value) }
  notify("Copied #{attribute} to clipboard. Clearing in 45 seconds", :normal, notification_seconds*1000)
  fork do
    File.write(clear_clip_pidfile, Process.pid)
    sleep(45)
    IO.popen(CONFIG.clip_command, 'w+') { |io| io.print('') }
    File.delete(clear_clip_pidfile)
  end
end

case return_value
when 0 then @entry.autotype!
when 10..15 then @entry.autotype!(return_value - 9)
when 16 then @entry.autotype_tan
when 17 then copy(CONFIG.password_key)
when 18 then copy(CONFIG.username_key)
when 19 then @entry.open_url!
when 20 then copy(:otp, 10)
end
